version: 2.1

jobs:

  build-backend:
    docker:
      - image: python:3.7.3-stretch
    working_directory: ./project    
    steps:
      - checkout
      - run:
          name: install dependencies
          command: |
            cd ./project
            pwd
            ls
            python3 -m venv venv
            . venv/bin/activate
            make install
      - save_cache:
          paths: [backend/project]
          key: backend-build

  test-backend:
    docker:
      - image: python:3.7.3-stretch
    steps:
      - checkout # Checkout code from git
      # Restore from cache
      - restore_cache:
          keys: [backend-build]
      - run:
          name: test-backend
          working_directory: ./project
          command: |
            python3 -m venv venv
            . venv/bin/activate
            make install
            # Install hadolint
            wget -O /bin/hadolint https://github.com/hadolint/hadolint/releases/download/v1.16.3/hadolint-Linux-x86_64 &&\
            chmod +x /bin/hadolint
            make lint

  docker-tag:
    docker:
      - image: circleci/python:3.7.3-stretch
    steps:
      - checkout # Checkout code from git
      - setup_remote_docker
      - restore_cache:
          keys: [backend-build]            
      - run:
          name: Build and push Docker image
          command: |
            cd project
            ls 
            docker build -t ricardofcapeli/capstone:latest .
            echo $DOCKER_PASS | docker login -u $DOCKER_USER --password-stdin
            docker push ricardofcapeli/capstone:latest        


workflows:
  default:
    jobs:
      - build-backend
      - test-backend:
          requires: [build-backend]
      - docker-tag:
          requires: [test-backend]             
