Description: >
    Capstone project for Cloud DevOps Engineering Nanodegree

Parameters:
  EnvironmentName:
    Description: An Environment name that will be prefixed to resources
    Type: String
Resources:
  CapstoneEKS:
    Type: AWS::EKS::Cluster
    Properties:
      Version: '1.18'
      RoleArn: arn:aws:iam::594121638925:role/Capstone
      ResourcesVpcConfig:
        SecurityGroupIds:
        - Fn::ImportValue:
            !Sub "${EnvironmentName}-SCG"
        SubnetIds:
            Fn::Split:
                - ","
                - Fn::ImportValue:
                      Fn::Sub: ${EnvironmentName}-SBN-IDS
Outputs:
  EksId:
    Description: The EKS id.
    Value: !Ref CapstoneEKS
    Export: 
        Name: !Sub ${EnvironmentName}-EKS


